Traceback (most recent call last):
  File "create_dataset.py", line 22, in <module>
    return_code = main()
  File "create_dataset.py", line 18, in main
    dataset.create_dataset()
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/DatasetManager.py", line 182, in create_dataset
    data = torch.stack(shuffled_configs, dim=0)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 6.01 GiB. GPU 0 has a total capacty of 23.67 GiB of which 3.79 GiB is free. Including non-PyTorch memory, this process has 19.80 GiB memory in use. Of the allocated memory 18.08 GiB is allocated by PyTorch, and 1.48 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Traceback (most recent call last):
  File "plot_dataset_info.py", line 178, in <module>
    return_code = main()
  File "plot_dataset_info.py", line 173, in main
    check_dataset_configs(saving_path, dataset, metadata)
  File "plot_dataset_info.py", line 118, in check_dataset_configs
    ax.imshow(config[img_idx].cpu(), cmap='gray')
  File "/home/bletchkey/.local/lib/python3.8/site-packages/matplotlib/__init__.py", line 1446, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/home/bletchkey/.local/lib/python3.8/site-packages/matplotlib/axes/_axes.py", line 5663, in imshow
    im.set_data(X)
  File "/home/bletchkey/.local/lib/python3.8/site-packages/matplotlib/image.py", line 710, in set_data
    raise TypeError("Invalid shape {} for image data"
TypeError: Invalid shape (1, 32, 32) for image data
Traceback (most recent call last):
  File "plot_dataset_info.py", line 177, in <module>
    return_code = main()
  File "plot_dataset_info.py", line 172, in main
    check_dataset_configs(saving_path, dataset, metadata)
  File "plot_dataset_info.py", line 115, in check_dataset_configs
    ax = axs[config_idx, img_idx]
IndexError: index 10 is out of bounds for axis 0 with size 10
plot_dataset_info.py:126: UserWarning: Tight layout not applied. tight_layout cannot make axes width small enough to accommodate all axes decorations
  plt.tight_layout()
Traceback (most recent call last):
  File "plot_dataset_info.py", line 222, in <module>
    return_code = main()
  File "plot_dataset_info.py", line 218, in main
    check_transient_phases(saving_path, metadata)
  File "plot_dataset_info.py", line 189, in check_transient_phases
    plt.bar(ids, transient_phases, color='blue')
  File "/home/bletchkey/.local/lib/python3.8/site-packages/matplotlib/pyplot.py", line 2439, in bar
    return gca().bar(
  File "/home/bletchkey/.local/lib/python3.8/site-packages/matplotlib/__init__.py", line 1446, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/home/bletchkey/.local/lib/python3.8/site-packages/matplotlib/axes/_axes.py", line 2486, in bar
    self.add_patch(r)
  File "/home/bletchkey/.local/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 2379, in add_patch
    self._update_patch_limits(p)
  File "/home/bletchkey/.local/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 2405, in _update_patch_limits
    vertices.append(curve([0, *dzeros, 1]))
KeyboardInterrupt
